project:
  type: website

website:
  title: "Rafli's Data Chronicles"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/belajaRProgramming0?tab=repositories
format:
  html:
    theme: journal
    css: styles.css
    include-after-body: _footer.Rhtml


