project:
  type: website

website:
  title: "Rafli's Data Chronicles"
  navbar:
    logo: "rlogofix.jpg"
    left:
      - href: index.html
    right:
      - text: Home
        href: index.qmd
      - text: Blog
        href: blog.qmd
      - about.qmd
      - icon: github
        href: https://github.com/belajaRProgramming0?tab=repositories
format:
  html:
    theme: journal
    css: styles.css
    include-in-header: _fonts.Rhtml
    include-after-body: _footer.Rhtml



